from selenium import webdriver
import time
driver = webdriver.Chrome()
driver.get('https://login.microsoftonline.com/common/oauth2/authorize?response_type=id_token&client_id=5e3ce6c0-2b1f-4285-8d4b-75ee78787346&redirect_uri=https%3A%2F%2Fteams.microsoft.com%2Fgo&state=77edf812-15c7-4cf4-9930-93989c56b27c&client-request-id=f1e75f81-c196-4b65-94da-a78b3724a0ea&x-client-SKU=Js&x-client-Ver=1.0.9&nonce=0a93e45f-0336-4db9-a9da-bfa722b772c4&domain_hint=&sso_reload=true')  
time.sleep(2)
login_id= driver.find_element_by_xpath('/html/body/div/form[1]/div/div/div[2]/div/div/div[1]/div[2]/div[2]/div/div/div/div[2]/div[2]/div/input[1]').send_keys('aman3639.be20@chitkara.edu.in')
time.sleep(2)
login_id_button= driver.find_element_by_xpath('/html/body/div/form[1]/div/div/div[2]/div/div/div[1]/div[2]/div[2]/div/div/div/div[4]/div/div/div/div/input').click()
time.sleep(2)
login_passward= driver.find_element_by_id('i0118').send_keys('*shivam2002#')
time.sleep(2)
login_pass_button=driver.find_element_by_xpath('/html/body/div/form[1]/div/div/div[2]/div/div/div[1]/div[2]/div[2]/div/div[2]/div/div[3]/div[2]/div/div/div/div/input').click()
time.sleep(2)
driver.find_element_by_xpath("/html/body/div/form/div/div/div[1]/div[2]/div/div[2]/div/div[3]/div[2]/div/div/div[2]/input").click()
time.sleep(20)
driver.find_element_by_xpath('/html/body/div[2]/div[2]/div[1]/div/left-rail/div/div/school-app-left-rail/channel-list/div/div[1]/ul/li[1]/ul/li[2]/div/div/ul/ng-include/li[2]/a/div[1]/span').click()
time.sleep(3)
driver.find_element_by_xpath('/html/body/div[2]/div[2]/div[2]/div[1]/middle-messages-stripe/div/messages-header/div[2]/div/message-pane/div/div[1]/div/div/message-list/div/virtual-repeat/div/div[9]/div/thread/div/div[2]/calling-thread-header/div/calling-join-button/button/span').click()
time.sleep(30)
driver.find_element_by_xpath('/html/body/div[5]/div[2]/div/div/div/div[1]/div/div/div[2]/div/button').click()
time.sleep(3)
driver.find_element_by_xpath('/html/body/div[2]/div[2]/div[2]/div[1]/div/calling-pre-join-screen/div/div/div[2]/div[1]/div[2]/div/div/section/div[1]/div/div/button').click()